"""The DiT workshop runs its model steps in a uv isolated environment.

No kernel install, no restart, hashed wheels only.

Static checks of the notebook, the carried stage file and the lock, plus the kernel/stage hand-off with a
model double (no torch, no network). Not execution evidence for a hosted runtime.
"""

import ast
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest
from PIL import Image

import build_document_classification_workshop_carrier as carrier
import document_classification_workshop as stages

ROOT = Path(__file__).resolve().parents[1]
NOTEBOOK = ROOT / "tutorials" / "DIMER_Document_Type_Classification_RVL_CDIP_Workshop.ipynb"
STAGE_FILE = ROOT / "tools" / "document_classification_workshop.py"
LOCK = ROOT / "tools" / "document-classification-workshop-requirements.lock"
REQUIREMENTS = ROOT / "tools" / "document-classification-workshop-requirements.in"
FORMER_PINS = {
    "torch": "2.14.0", "torchvision": "0.29.0", "torchaudio": "2.11.0", "transformers": "4.57.6",
    "safetensors": "0.8.0", "numpy": "2.1.3", "pillow": "11.3.0", "huggingface-hub": "0.36.2",
    "datasets": "4.1.1",
}
# The kernel may import only the standard library and what hosted runtimes ship.
KERNEL_IMPORTS = {"ast", "collections", "csv", "datetime", "hashlib", "io", "json", "math", "os", "platform",
                  "subprocess", "sys", "tempfile", "time", "urllib", "zipfile", "pathlib", "IPython", "numpy",
                  "PIL"}


def _notebook():
    return json.loads(NOTEBOOK.read_text(encoding="utf-8"))


def _code_cells():
    return [(c["id"], "".join(c["source"])) for c in _notebook()["cells"] if c["cell_type"] == "code"]


def _src(cid):
    return next(s for i, s in _code_cells() if i == cid)


def test_no_kernel_install_or_restart_guard():
    for cid, source in _code_cells():
        if cid == "uvcarrier":
            continue
        assert not re.search(r"-m\W+pip|^\s*[%!]\s*pip", source, re.M), cid
        for install in re.findall(r'"pip", "install"[^\n]*', source):
            assert '"--python", str(PYTHON)' in install, (cid, install)  # into the venv only
        for banned in ("Restart session", "sys.executable", "importlib.metadata", "check_call"):
            assert banned not in source, (cid, banned)
    markdown = "\n".join("".join(c["source"]) for c in _notebook()["cells"] if c["cell_type"] == "markdown")
    assert "no restart" in markdown.lower() and "Linux x86_64 only" in markdown
    assert "Restart session" not in markdown


def test_kernel_imports_only_the_standard_library_and_hosted_packages():
    for cid, source in _code_cells():
        for node in ast.walk(ast.parse(source)):
            if isinstance(node, ast.Import):
                names = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                names = [node.module or ""]
            else:
                continue
            for name in names:
                assert name.split(".")[0] in KERNEL_IMPORTS, (cid, name)


def test_lock_has_hashes_for_every_requirement_and_keeps_the_former_pins():
    text = LOCK.read_text(encoding="utf-8")
    hashed = r"((?:    --hash=sha256:[0-9a-f]{64}(?: \\)?\n)+)"
    blocks = re.findall(r"^([A-Za-z0-9_.-]+)==(\S+) \\\n" + hashed, text, re.M)
    pinned = {name.lower(): version for name, version, _ in blocks}
    requirement_lines = [ln for ln in text.splitlines() if re.match(r"^[A-Za-z0-9_.-]+==", ln)]
    assert len(blocks) == len(requirement_lines) >= 40
    for name, version in FORMER_PINS.items():
        assert pinned[name] == version, name
        assert f"{name} {version}" in text.split("# This file was autogenerated")[0], name
    direct = dict(ln.split("==") for ln in REQUIREMENTS.read_text(encoding="utf-8").splitlines()
                  if ln and not ln.startswith("#"))
    assert direct == FORMER_PINS == stages.PINS
    assert "--python-platform x86_64-manylinux_2_28" in text and "--only-binary :all:" in text


def test_runtime_cell_pins_uv_and_installs_with_require_hashes_only_binary():
    source = _src("442373b0")
    assert '"--require-hashes", "--only-binary", ":all:"' in source
    assert "uv-0.12.15-py3-none-manylinux_2_17_x86_64" in source
    assert 'UV_SHA256 = "aee9802f46bae436bd91751bb33ddeb379ef1596b5c19df193219d545d244b60"' in source
    assert '"venv", "--clear", "--managed-python", "--python", "3.12.12"' in source
    assert 'platform.system() != "Linux" or platform.machine() != "x86_64"' in source
    assert 'ENV["MPLBACKEND"] = "Agg"' in source
    assert '("HF_TOKEN", "HUGGING_FACE_HUB_TOKEN", "PYTHONPATH", "PYTHONHOME", "PYTHONSTARTUP")' in source


def test_stages_run_with_the_venv_python():
    source = _src("442373b0")
    assert 'PYTHON = ENV_ROOT / "bin" / "python"' in source
    assert 'command = [str(PYTHON), "-u", str(STAGE_SCRIPT), "--config"' in source
    assert 'STAGE_SCRIPT = RUNNER_ROOT / "document_classification_workshop.py"' in source
    called = set()
    for _, cell in _code_cells():
        called.update(re.findall(r'run_stage\(\s*"([a-z0-9-]+)"', cell))
    assert called == set(stages.STAGES)


def test_model_libraries_are_used_only_by_the_stage_file():
    for cid, source in _code_cells():
        if cid == "uvcarrier":
            continue
        for library in ("torch", "transformers", "datasets", "huggingface_hub", "safetensors"):
            assert not re.search(rf"^\s*(import|from)\s+{library}\b", source, re.M), (cid, library)


def test_no_cell_line_is_longer_than_2000_characters():
    for cell in _notebook()["cells"]:
        for line in "".join(cell["source"]).splitlines():
            assert len(line) <= 2000, (cell["id"], len(line))


def test_carried_literals_are_pieces_of_at_most_1000_characters_equal_to_the_files():
    tree = ast.parse(_src("uvcarrier"))
    files = next(node.value for node in tree.body if isinstance(node, ast.Assign)
                 and node.targets[0].id == "CARRIED_FILES")
    for key, value in zip(files.keys, files.values, strict=True):
        name = ast.literal_eval(key)
        segment = ast.get_source_segment(_src("uvcarrier"), value)
        pieces = [ast.literal_eval(line.strip()) for line in segment.strip("()").splitlines() if line.strip()]
        assert pieces and all(len(piece) <= 1000 for piece in pieces), name
        assert "".join(pieces) == ast.literal_eval(value) == carrier.CARRIED[name].read_text(encoding="utf-8")


def test_carrier_pieces_split_long_lines():
    text = "a" * 2500 + "\nshort\n"
    parts = carrier.pieces(text)
    assert "".join(parts) == text and max(len(p) for p in parts) <= 1000


def test_carrier_cell_matches_the_tools_files():
    assert carrier.main(["--check"]) == 0
    carried = _notebook()["metadata"]["dimer"]["carried_files"]
    assert carried["document_classification_workshop.py"]["sha256"] == hashlib.sha256(
        STAGE_FILE.read_bytes()).hexdigest()
    assert carried["requirements.lock.txt"]["sha256"] == hashlib.sha256(LOCK.read_bytes()).hexdigest()
    order = [c["id"] for c in _notebook()["cells"]]
    assert order.index("73612e03") < order.index("uvcarrier") < order.index("442373b0")


def test_carrier_cell_writes_files_that_hash_to_the_lock(tmp_path):
    ns = {"WORK_DIR": str(tmp_path / "work")}
    exec(compile(_src("uvcarrier"), "uvcarrier", "exec"), ns)
    runner = tmp_path / "work" / "runner"
    assert (runner / "document_classification_workshop.py").read_bytes() == STAGE_FILE.read_bytes()
    assert (runner / "requirements.lock.txt").read_bytes() == LOCK.read_bytes()


def test_uv_revision_is_logged_in_the_notebook_metadata():
    revisions = _notebook()["metadata"]["dimer"]["review_revisions"]
    entry = next(r for r in revisions if r["date"] == "2026-10-03")
    assert entry["change"] == "uv isolated environment" and entry["hosted_execution"] == "pending"
    assert entry["pins_changed"] == "none"


def test_docs_say_linux_x86_64_only():
    row = next(ln for ln in (ROOT / "tutorials" / "README.md").read_text(encoding="utf-8").splitlines()
               if NOTEBOOK.name in ln and ln.startswith("|"))
    assert "Linux x86_64 only" in row and "| Candidate" in row.replace("**", "")
    verification = (ROOT / "docs" / "release-verification.md").read_text(encoding="utf-8")
    assert "2026-10-03 uv isolated environment" in verification


# ---- kernel <-> stage hand-off with a model double --------------------------------------------------------
def _kernel_predict(tmp_path, monkeypatch):
    """The notebook's batched_predict, wired in-process to the stage file with a model double."""
    scored = []

    def double(_processor, _model, records, batch_size):
        scored.append([r["image"].size for r in records])
        scores = np.full((len(records), 16), 0.2 / 15, dtype=np.float32)
        scores[:, 4] = 0.8
        return np.log(scores), scores, [0.0] * -(-len(records) // batch_size), None

    monkeypatch.setattr(stages, "load_converted_model", lambda: (None, None, 0.0))
    monkeypatch.setattr(stages, "batched_predict", double)
    monkeypatch.setattr(stages, "device", lambda: "cpu")
    stage_calls = []

    def run_stage(stage, *options, **_settings):
        stage_calls.append((stage, options))
        assert stage == "predict" and options[0] == "--job"
        stages.stage_predict(options[1])

    tree = ast.parse(_src("b485b2eb"))
    tree.body = [node for node in tree.body if isinstance(node, ast.FunctionDef)
                 and node.name in {"batched_predict", "rank_classes"}]
    ns = {"Path": Path, "Image": Image, "np": np, "json": json, "tempfile": __import__("tempfile"),
          "WORK_ROOT": tmp_path / "work", "BATCH_SIZE": 16, "run_stage": run_stage,
          "read_json": lambda path: json.loads(Path(path).read_text(encoding="utf-8"))}
    exec(compile(tree, "b485b2eb", "exec"), ns)
    return ns, scored, stage_calls


def test_kernel_batched_predict_round_trips_pages_through_the_stage(tmp_path, monkeypatch):
    ns, scored, stage_calls = _kernel_predict(tmp_path, monkeypatch)
    page = tmp_path / "page.png"
    Image.new("RGB", (60, 80), "white").save(page)
    records = [{"image_id": "a", "png": str(page), "image": Image.open(page).convert("RGB")},
               {"image_id": "b", "image": Image.new("RGB", (50, 70), "black")}]
    logits, scores, timings, peak = ns["batched_predict"](records, batch_size=1)
    assert len(stage_calls) == 1 and scored == [[(60, 80), (50, 70)]]
    assert scores.shape == (2, 16) and logits.shape == (2, 16) and timings == [0.0, 0.0] and peak is None
    assert ns["rank_classes"](scores)[:, 0].tolist() == [4, 4]


@pytest.mark.parametrize("variant", stages.ROBUSTNESS_VARIANTS)
def test_variants_are_made_in_the_stage_and_returned_for_display(tmp_path, monkeypatch, variant):
    ns, scored, _calls = _kernel_predict(tmp_path, monkeypatch)
    page = tmp_path / "page.png"
    base = Image.new("RGB", (60, 80), "white")
    base.putpixel((0, 0), (10, 20, 30))
    base.save(page)
    record = {"image_id": "a", "png": str(page), "image": base, "variant": variant}
    ns["batched_predict"]([record], batch_size=16)
    expected = stages.transform_variant(base, variant)
    assert scored == [[expected.size]]
    assert record["image"].size == expected.size and record["image"].tobytes() == expected.tobytes()


def test_transform_variant_rejects_unknown_variants():
    with pytest.raises(ValueError):
        stages.transform_variant(Image.new("RGB", (40, 40)), "mirror")


def test_sample_selection_is_the_seeded_per_class_ranking():
    labels = [i % 16 for i in range(16 * 30)]
    chosen = stages.select_sample_indices(labels, 42, 20)
    assert len(chosen) == 320 and chosen == sorted(chosen)
    for label_id in range(16):
        rows = [i for i in range(len(labels)) if labels[i] == label_id]
        ranked = sorted(rows, key=lambda i: hashlib.sha256(f"42:{i}:{label_id}".encode()).hexdigest())
        assert sorted(ranked[:20]) == [i for i in chosen if labels[i] == label_id]
    with pytest.raises(RuntimeError, match="has only"):
        stages.select_sample_indices(labels[:16 * 19], 42, 20)


def test_stage_command_line_rejects_unknown_stages_and_a_predict_without_a_job(tmp_path):
    config = tmp_path / "config.json"
    config.write_text(json.dumps({"work_dir": str(tmp_path / "work")}), encoding="utf-8")
    command = [sys.executable, str(STAGE_FILE), "--config", str(config), "--stage"]
    unknown = subprocess.run([*command, "train"], capture_output=True, text=True, timeout=60)
    assert unknown.returncode == 2 and "invalid choice" in unknown.stderr
    no_job = subprocess.run([*command, "predict"], capture_output=True, text=True, timeout=60)
    assert no_job.returncode == 2 and "--job is required" in no_job.stderr
