"""DIMER DiT document-type classification pipeline."""

from .pipeline import (
    CLASS_NAMES,
    DECISION_RULE,
    DEFAULT_WEIGHTS_DIR,
    INPUT_SCHEMA,
    MAX_BATCH,
    MAX_IMAGE_SIDE,
    MAX_PIXELS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    NUM_CLASSES,
    SERVING_FILENAME,
    SOURCE_BYTES,
    SOURCE_FILENAME,
    SOURCE_SHA256,
    DiTDocumentClassificationPipeline,
    classification_metrics,
    sha256_file,
    validate_dataset,
    validate_inputs,
    verify_snapshot,
)

__all__ = [
    "CLASS_NAMES",
    "DECISION_RULE",
    "DEFAULT_WEIGHTS_DIR",
    "INPUT_SCHEMA",
    "MAX_BATCH",
    "MAX_IMAGE_SIDE",
    "MAX_PIXELS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "NUM_CLASSES",
    "SERVING_FILENAME",
    "SOURCE_BYTES",
    "SOURCE_FILENAME",
    "SOURCE_SHA256",
    "DiTDocumentClassificationPipeline",
    "classification_metrics",
    "sha256_file",
    "validate_dataset",
    "validate_inputs",
    "verify_snapshot",
]
